plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

RSpec/ExampleLength:
  CountAsOne:
    - method_call

Style/StringLiterals:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

# Linters to disable because Standard applies them differently:

Layout/ArgumentAlignment:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false
