name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.0, 3.1, 3.2, 3.3, 3.4]

    container:
      image: ruby:${{ matrix.ruby }}-alpine

    steps:
      - name: Install build tools
        run: apk add --no-cache build-base git

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install Bundler and gems
        run: |
          gem install bundler
          bundle install

      - name: Run RSpec tests
        run: bundle exec rspec
